bubble_sort
jcromerohdz/bubble_sort pull request #1
Opened 2019-10-11 15:56 UTC by jcromerohdz

… file

2019-10-12 05:51 UTC, Ispirett requested changes
Hey @jcromerohdz great work so far :+1:  :+1: 

**There are just some bugs :bug: to be fixed**

```
) bubble_sort_by sorts an array by accepting a block
     Failure/Error: expect(bubble_sort_by(unsorted) { |left, right| left.length - right.length }).to eq %w[hi hey hello]
     
       expected: ["hi", "hey", "hello"]
            got: nil
     
       (compared using ==)
     # ./spec/bubble_sort_spec.rb:16:in `block (2 levels) in <top (required)>'

  2) bubble_sort_by raises an error if block is not given
     Failure/Error: expect { bubble_sort_by(unsorted) }.to raise_error
       expected Exception but nothing was raised
     # ./spec/bubble_sort_spec.rb:20:in `block (2 levels) in <top
``

2019-10-12 16:31 UTC, jcromerohdz commented
How do you tested?, please give your test in order to replicate the error

2019-10-15 01:13 UTC, Ispirett requested changes
Hey, @jcromerohdz   @flov3rh great work with trying to address the issues but some still persists.
 please check the comments below.

2019-10-15 01:13 UTC, Ispirett commented on bubble_sort.rb
> +end
bubble_sort_by(%w[hi hello hey]) { |left, right| left.length - right.length }) === %w[hi hey hello]
  
bubble_sort_by(%w[hi hello hey]) this should raise an error because no block of  code was given

2019-10-15 01:13 UTC, Ispirett commented on bubble_sort.rb
> +end
1) bubble_sort_by sorts an array by accepting a block
     Failure/Error: expect(bubble_sort_by(unsorted) { |left, right| left.length - right.length }).to eq %w[hi hey hello]
     
       expected: ["hi", "hey", "hello"]
            got: nil
     
       (compared using ==)

  2) bubble_sort_by raises an error if block is not given
     Failure/Error: expect { bubble_sort_by(unsorted) }.to raise_error
       expected Exception but nothing was raised

2019-10-15 16:56 UTC, maelfosso approved these changes
# Congratulation :clap:  You did it :smile: 

**The project is approved**  :+1: 
Correct the comment I left below and merge.

Good luck with the next project

2019-10-15 16:56 UTC, maelfosso commented on bubble_sort.rb
> +  output
No need to do that.
Just return `arr`, an array

2019-10-15 17:01 UTC, merged